@extends('layouts.app')

@section('page-title', $lead->exists ? 'Edit Lead' : 'Add Lead')

@section('content')
@push('styles')
    <link rel="stylesheet" href="{{ asset('assets/css/leads.css') }}">
@endpush
@php($isEdit = $lead->exists)
<div class="lm-form">
    <div class="lm-card lm-header"><h1>{{ $isEdit ? 'Edit Lead' : 'Add Lead' }}</h1><div class="lm-breadcrumb"><a href="{{ url('/') }}">Home</a><span>•</span><a href="{{ route('leads.index') }}">Leads</a><span>•</span><span class="active">{{ $isEdit ? 'Edit' : 'Add' }}</span></div></div>
    <form class="lm-card lm-form-card" method="POST" action="{{ $isEdit ? route('leads.update', $lead) : route('leads.store') }}" enctype="multipart/form-data">@csrf @if($isEdit) @method('PUT') @endif
        <div class="lm-section"><h3 class="lm-section-title">Lead Basic Information</h3><div class="lm-grid"><div><label class="lm-label">Lead Number</label><input class="lm-input" name="lead_number" value="{{ old('lead_number',$lead->lead_number) }}" placeholder="Auto generated"></div><div class="lm-field two"><label class="lm-label">Lead Title <span class="lm-required">*</span></label><input class="lm-input" name="title" value="{{ old('title',$lead->title) }}" required></div><div><label class="lm-label">Status</label><select class="lm-select" name="status">@foreach($statusOptions as $key=>$label)<option value="{{ $key }}" @selected(old('status',$lead->status)===$key)>{{ $label }}</option>@endforeach</select></div><div><label class="lm-label">Priority</label><select class="lm-select" name="priority">@foreach($priorityOptions as $key=>$label)<option value="{{ $key }}" @selected(old('priority',$lead->priority)===$key)>{{ $label }}</option>@endforeach</select></div><div><label class="lm-label">Source</label><select class="lm-select" name="lead_source">@foreach($sourceOptions as $key=>$label)<option value="{{ $key }}" @selected(old('lead_source',$lead->lead_source)===$key)>{{ $label }}</option>@endforeach</select></div><div><label class="lm-label">Assigned To</label><select class="lm-select" name="assigned_to"><option value="">Unassigned</option>@foreach($users as $user)<option value="{{ $user->id }}" @selected((string)old('assigned_to',$lead->assigned_to)===(string)$user->id)>{{ $user->name ?? $user->email }}</option>@endforeach</select></div></div></div>
        <div class="lm-section"><h3 class="lm-section-title">Client Details</h3><div class="lm-grid"><div><label class="lm-label">Linked Client</label><select class="lm-select" name="client_id"><option value="">No linked client</option>@foreach($clients as $client)<option value="{{ $client->id }}" @selected((string)old('client_id',$lead->client_id)===(string)$client->id)>{{ $client->company_name }}</option>@endforeach</select></div><div><label class="lm-label">Client Company</label><input class="lm-input" name="client_company_name" value="{{ old('client_company_name',$lead->client_company_name) }}"></div><div><label class="lm-label">Contact Name</label><input class="lm-input" name="client_contact_name" value="{{ old('client_contact_name',$lead->client_contact_name) }}"></div><div><label class="lm-label">Email</label><input class="lm-input" type="email" name="client_email" value="{{ old('client_email',$lead->client_email) }}"></div><div><label class="lm-label">Mobile</label><input class="lm-input" name="client_mobile" value="{{ old('client_mobile',$lead->client_mobile) }}"></div></div></div>
        <div class="lm-section"><h3 class="lm-section-title">Product Requirement</h3><div class="lm-grid"><div>@if($lead->product_image_path)<a href="{{ route('leads.image', $lead) }}" title="View product image"><img class="lm-preview" src="{{ asset('storage/'.$lead->product_image_path) }}"></a>@else<span class="lm-preview">📦</span>@endif</div><div><label class="lm-label">Product Image</label><input class="lm-input" type="file" name="product_image" accept="image/*"></div><div><label class="lm-label">Product Name</label><input class="lm-input" name="product_name" value="{{ old('product_name',$lead->product_name) }}"></div><div><label class="lm-label">Capacity</label><input class="lm-input" type="number" step="0.001" name="capacity_value" value="{{ old('capacity_value',$lead->capacity_value) }}"></div><div><label class="lm-label">Capacity Unit</label><input class="lm-input" name="capacity_unit" value="{{ old('capacity_unit',$lead->capacity_unit ?: 'ml') }}"></div><div><label class="lm-label">Required Quantity</label><input class="lm-input" type="number" name="required_quantity" value="{{ old('required_quantity',$lead->required_quantity) }}"></div><div><label class="lm-label">Quote Quantities</label><input class="lm-input" name="quote_quantities_text" value="{{ old('quote_quantities_text', implode(',', $lead->quote_quantities ?? [])) }}" placeholder="3000,5000,10000"></div><div class="lm-field full"><label class="lm-label">Product Description</label><textarea class="lm-textarea" name="product_description">{{ old('product_description',$lead->product_description) }}</textarea></div><div class="lm-field full"><label class="lm-label">Quantity Notes</label><textarea class="lm-textarea" name="quantity_notes">{{ old('quantity_notes',$lead->quantity_notes) }}</textarea></div></div></div>
        <div class="lm-section"><h3 class="lm-section-title">Finish, Printing & Stock</h3><div class="lm-grid"><div><label class="lm-label">Finish Required</label><select class="lm-select" name="finish_required"><option value="">Select</option>@foreach($finishOptions as $key=>$label)<option value="{{ $key }}" @selected(old('finish_required',$lead->finish_required)===$key)>{{ $label }}</option>@endforeach</select></div><div><label class="lm-label">Printing Required</label><select class="lm-select" name="printing_required"><option value="">Select</option>@foreach($printingOptions as $key=>$label)<option value="{{ $key }}" @selected(old('printing_required',$lead->printing_required)===$key)>{{ $label }}</option>@endforeach</select></div><label class="lm-check"><input type="checkbox" name="ready_stock_required" value="1" @checked(old('ready_stock_required',$lead->ready_stock_required))> Ready Stock Required</label><label class="lm-check"><input type="checkbox" name="custom_color_required" value="1" @checked(old('custom_color_required',$lead->custom_color_required))> Custom Color Required</label><div class="lm-field full"><label class="lm-label">Printing Details</label><textarea class="lm-textarea" name="printing_details">{{ old('printing_details',$lead->printing_details) }}</textarea></div><div class="lm-field full"><label class="lm-label">Ready Stock Colors / MOQ Requirement</label><textarea class="lm-textarea" name="ready_stock_color_requirement">{{ old('ready_stock_color_requirement',$lead->ready_stock_color_requirement) }}</textarea></div><div class="lm-field full"><label class="lm-label">Custom Color Specification</label><textarea class="lm-textarea" name="custom_color_specification">{{ old('custom_color_specification',$lead->custom_color_specification) }}</textarea></div></div></div>
        <div class="lm-section"><h3 class="lm-section-title">Commercial & Notes</h3><div class="lm-grid"><div><label class="lm-label">Target Price</label><input class="lm-input" type="number" step="0.01" name="target_price" value="{{ old('target_price',$lead->target_price) }}"></div><div><label class="lm-label">Currency</label><select class="lm-select" name="target_currency">@foreach($currencyOptions as $key=>$label)<option value="{{ $key }}" @selected(old('target_currency',$lead->target_currency)===$key)>{{ $label }}</option>@endforeach</select></div><div><label class="lm-label">Expected Order Date</label><input class="lm-input" type="date" name="expected_order_date" value="{{ old('expected_order_date', optional($lead->expected_order_date)->format('Y-m-d')) }}"></div><div><label class="lm-label">Required Delivery Date</label><input class="lm-input" type="date" name="required_delivery_date" value="{{ old('required_delivery_date', optional($lead->required_delivery_date)->format('Y-m-d')) }}"></div><div class="lm-field full"><label class="lm-label">Sales Notes</label><textarea class="lm-textarea" name="sales_notes">{{ old('sales_notes',$lead->sales_notes) }}</textarea></div><div class="lm-field full"><label class="lm-label">Purchase Notes</label><textarea class="lm-textarea" name="purchase_notes">{{ old('purchase_notes',$lead->purchase_notes) }}</textarea></div></div></div>
        <div class="lm-section"><h3 class="lm-section-title">Attachments</h3><div class="lm-grid"><div class="lm-field full"><label class="lm-label">Upload Photos / Videos / Documents</label><input class="lm-input" type="file" name="attachments[]" multiple></div><div class="lm-field full"><label class="lm-label">External Photo / Video Links</label><textarea class="lm-textarea" name="attachment_links" placeholder="One URL per line"></textarea></div></div></div>
        <div class="lm-actions"><a href="{{ $isEdit ? route('leads.show',$lead) : route('leads.index') }}" class="lm-btn lm-btn-light">Cancel</a><button class="lm-btn lm-btn-primary" type="submit">{{ $isEdit ? 'Update Lead' : 'Create Lead' }}</button></div>
    </form>
</div>
@endsection
