@extends('client_portal.layouts.app')

@section('title', $invoice->invoice_number)
@section('page-title', 'Invoice Detail')

@section('content')
<div class="cp-page-head"><div><p class="cp-eyebrow">Invoice</p><h1>{{ $invoice->invoice_number }}</h1><p>{{ $invoice->title ?: 'Invoice' }} · {{ $invoice->statusLabel() }}</p></div><div style="display:flex;gap:10px;flex-wrap:wrap;">@if($invoice->fileUrl())<a href="{{ $invoice->fileUrl() }}" target="_blank" class="cp-btn cp-btn-primary">Download Invoice</a>@endif<a href="{{ route('client-portal.invoices.index') }}" class="cp-btn cp-btn-light">Back</a></div></div>
<div class="cp-grid-4" style="margin-bottom:18px;"><div class="cp-card cp-stat"><span>Total</span><strong>{{ $invoice->currency }} {{ number_format((float)$invoice->total_amount, 2) }}</strong></div><div class="cp-card cp-stat"><span>Paid</span><strong>{{ $invoice->currency }} {{ number_format((float)$invoice->paid_amount, 2) }}</strong></div><div class="cp-card cp-stat"><span>Outstanding</span><strong>{{ $invoice->currency }} {{ number_format($invoice->outstandingAmount(), 2) }}</strong></div><div class="cp-card cp-stat"><span>Status</span><strong>{{ $invoice->statusLabel() }}</strong></div></div>
<div class="cp-grid-2"><div class="cp-card" style="padding:20px;"><p class="cp-eyebrow">Details</p><h2 style="margin-top:0;">Invoice Information</h2><p><strong>Invoice Date:</strong> {{ optional($invoice->invoice_date)->format('d M Y') ?: '-' }}</p><p><strong>Due Date:</strong> {{ optional($invoice->due_date)->format('d M Y') ?: '-' }}</p><p><strong>Subtotal:</strong> {{ $invoice->currency }} {{ number_format((float)$invoice->subtotal, 2) }}</p><p><strong>Tax:</strong> {{ $invoice->currency }} {{ number_format((float)$invoice->tax_amount, 2) }}</p><p><strong>Notes:</strong><br>{{ $invoice->notes ?: '-' }}</p></div><div class="cp-card" style="padding:20px;"><p class="cp-eyebrow">Comments</p><h2 style="margin-top:0;">Invoice Discussion</h2><form method="POST" action="{{ route('client-portal.invoices.comments.store', $invoice) }}" style="margin-bottom:15px;">@csrf<div class="cp-field"><label>Comment</label><textarea name="body" required></textarea></div><button class="cp-btn cp-btn-primary" style="margin-top:10px;">Submit Comment</button></form>@forelse($comments as $comment)<div class="cp-comment"><div class="cp-comment-head"><strong>{{ $comment->authorName() }}</strong><span>{{ $comment->created_at->format('d M Y, h:i A') }}</span></div><p>{{ $comment->body }}</p></div>@empty<div class="cp-empty">No comments yet.</div>@endforelse</div></div>
@endsection
