@extends('client_portal.layouts.app')

@section('title', 'Attachments')
@section('page-title', 'Attachments')

@section('content')
<div class="cp-page-head"><div><p class="cp-eyebrow">Documents</p><h1>Attachments</h1><p>Upload and view documents shared through the client portal.</p></div></div>
<div class="cp-grid-2">
    <div class="cp-card" style="padding:20px;"><p class="cp-eyebrow">Upload</p><h2 style="margin-top:0;">Upload Documents</h2><form method="POST" action="{{ route('client-portal.attachments.store') }}" enctype="multipart/form-data" class="cp-form-grid">@csrf<div class="master-field"><label class="master-label">Category</label><select class="master-select" name="category" required>@foreach($categories as $key=>$label)<option value="{{ $key }}">{{ $label }}</option>@endforeach</select></div><div class="master-field"><label class="master-label">Related To</label><select class="master-select" name="related_type"><option value="general">General</option><option value="project">Project</option><option value="shipment">Shipment</option><option value="quote">Quotation</option><option value="invoice">Invoice</option><option value="kyc">KYC</option></select></div><div class="master-field"><label class="master-label">Related ID</label><input class="master-input" type="number" name="related_id" placeholder="Optional"></div><div class="master-field"><label class="master-label">Title</label><input class="master-input" name="title"></div><div class="master-field" style="grid-column:1/-1;"><label class="master-label">Files</label><input class="master-input" type="file" name="attachments[]" multiple required></div><div class="master-field" style="grid-column:1/-1;"><label class="master-label">Notes</label><textarea class="master-textarea" name="notes"></textarea></div><button class="master-btn master-btn-primary" style="grid-column:1/-1;">Upload</button></form></div>
    <div class="cp-card" style="padding:20px;"><p class="cp-eyebrow">Filter</p><h2 style="margin-top:0;">Document Filter</h2><form method="GET" class="cp-form-grid"><div class="master-field"><label class="master-label">Category</label><select class="master-select" name="category"><option value="all">All Categories</option>@foreach($categories as $key=>$label)<option value="{{ $key }}" {{ $category===$key?'selected':'' }}>{{ $label }}</option>@endforeach</select></div><div style="display:flex;align-items:end;gap:10px;"><button class="master-btn master-btn-primary">Filter</button><a class="master-btn master-btn-light" href="{{ route('client-portal.attachments.index') }}">Reset</a></div></form></div>
</div>
<div class="cp-card" style="padding:20px;margin-top:18px;"><p class="cp-eyebrow">Files</p><h2 style="margin-top:0;">Uploaded Documents</h2><div class="cp-grid-2">@forelse($documents as $document)<div class="cp-file">@if($document->isImage())<img src="{{ $document->fileUrl() }}">@else<div class="cp-file-icon">▤</div>@endif<div><strong>{{ $document->title ?: $document->original_name }}</strong><div class="cp-muted">{{ $document->categoryLabel() }} · {{ strtoupper($document->extension) }} · {{ $document->created_at->format('d M Y') }}</div><div style="display:flex;gap:8px;margin-top:8px;"><a class="master-btn master-btn-soft master-btn-sm" href="{{ $document->fileUrl() }}" target="_blank">Open</a><form method="POST" action="{{ route('client-portal.attachments.destroy', $document) }}" onsubmit="return confirm('Delete this document?')">@csrf @method('DELETE')<button class="master-btn master-btn-light master-btn-sm" type="submit">Delete</button></form></div></div></div>@empty<div class="cp-empty" style="grid-column:1/-1;">No documents uploaded yet.</div>@endforelse</div><div class="cp-pagination">{{ $documents->links() }}</div></div>
@endsection
