@extends('layouts.app')

@section('page-title', $quote->exists ? 'Edit Customer Quote' : 'Create Customer Quote')

@section('content')
@push('styles')
    <link rel="stylesheet" href="{{ asset('assets/css/lead-quotes-form.css') }}">
@endpush
@php($isEdit = $quote->exists)
@php($items = old('items') ?? $quote->items->map(function($item){ return $item->only(['product_name','description','quantity','unit','capacity','finish_type','printing_type','unit_price','remarks']); })->toArray())
@if(empty($items)) @php($items=[['product_name'=>$quote->lead?->product_name,'description'=>'','quantity'=>$quote->lead?->required_quantity ?: 1,'unit'=>'pcs','capacity'=>$quote->lead?->capacity_value ? $quote->lead->capacity_value.' '.$quote->lead->capacity_unit : '','finish_type'=>$quote->lead?->finish_required,'printing_type'=>$quote->lead?->printing_required,'unit_price'=>'','remarks'=>'']]) @endif
<div class="cq-form"><div class="cq-card cq-header"><h1>{{ $isEdit ? 'Edit Customer Quote' : 'Create Customer Quote' }}</h1><div><a href="{{ route('lead-quotes.index') }}" class="cq-btn cq-btn-light">Back</a></div></div>@if($errors->any())<div class="cq-alert">{{ $errors->first() }}</div>@endif
<form method="POST" action="{{ $isEdit ? route('lead-quotes.update',$quote) : route('lead-quotes.store') }}" class="cq-card cq-form-card">@csrf @if($isEdit) @method('PUT') @endif
<div class="cq-section"><h3 class="cq-section-title">Quote Details</h3><div class="cq-grid"><div><label class="cq-label">Quote Number</label><input class="cq-input" name="quote_number" value="{{ old('quote_number',$quote->quote_number) }}" placeholder="Auto generated"></div><div><label class="cq-label">Lead</label><select class="cq-select" name="lead_id"><option value="">Standalone Quote</option>@foreach($leads as $leadOption)<option value="{{ $leadOption->id }}" @selected((string)old('lead_id',$quote->lead_id)===(string)$leadOption->id)>{{ $leadOption->lead_number }} - {{ $leadOption->title }}</option>@endforeach</select></div><div><label class="cq-label">Status</label><select class="cq-select" name="status">@foreach($statusOptions as $key=>$label)<option value="{{ $key }}" @selected(old('status',$quote->status)===$key)>{{ $label }}</option>@endforeach</select></div><div class="cq-field two"><label class="cq-label">Title</label><input class="cq-input" name="title" value="{{ old('title',$quote->title) }}" required></div><div><label class="cq-label">Currency</label><select class="cq-select" name="currency">@foreach($currencyOptions as $key=>$label)<option value="{{ $key }}" @selected(old('currency',$quote->currency)===$key)>{{ $label }}</option>@endforeach</select></div><div><label class="cq-label">Quote Date</label><input class="cq-input" type="date" name="quote_date" value="{{ old('quote_date', optional($quote->quote_date)->format('Y-m-d')) }}"></div><div><label class="cq-label">Valid Until</label><input class="cq-input" type="date" name="valid_until" value="{{ old('valid_until', optional($quote->valid_until)->format('Y-m-d')) }}"></div></div></div>
<div class="cq-section"><h3 class="cq-section-title">Customer Details</h3><div class="cq-grid"><div><label class="cq-label">Linked Client</label><select class="cq-select" name="client_id"><option value="">No client</option>@foreach($clients as $client)<option value="{{ $client->id }}" @selected((string)old('client_id',$quote->client_id)===(string)$client->id)>{{ $client->company_name }}</option>@endforeach</select></div><div><label class="cq-label">Company</label><input class="cq-input" name="customer_company_name" value="{{ old('customer_company_name',$quote->customer_company_name) }}"></div><div><label class="cq-label">Contact</label><input class="cq-input" name="customer_contact_name" value="{{ old('customer_contact_name',$quote->customer_contact_name) }}"></div><div><label class="cq-label">Email</label><input class="cq-input" type="email" name="customer_email" value="{{ old('customer_email',$quote->customer_email) }}"></div><div><label class="cq-label">Mobile</label><input class="cq-input" name="customer_mobile" value="{{ old('customer_mobile',$quote->customer_mobile) }}"></div></div></div>
<div class="cq-section"><h3 class="cq-section-title">Quote Items</h3><div class="cq-items"><table class="cq-table" id="quoteItemsTable" data-item-count="{{ count($items) }}"><thead><tr><th>Product</th><th>Description</th><th>Qty</th><th>Unit</th><th>Capacity</th><th>Finish</th><th>Printing</th><th>Unit Price</th><th>Remarks</th><th></th></tr></thead><tbody>@foreach($items as $i=>$item)<tr><td><input class="cq-input" name="items[{{ $i }}][product_name]" value="{{ $item['product_name'] ?? '' }}"></td><td><input class="cq-input" name="items[{{ $i }}][description]" value="{{ $item['description'] ?? '' }}"></td><td><input class="cq-input" type="number" step="0.001" name="items[{{ $i }}][quantity]" value="{{ $item['quantity'] ?? 1 }}"></td><td><input class="cq-input" name="items[{{ $i }}][unit]" value="{{ $item['unit'] ?? 'pcs' }}"></td><td><input class="cq-input" name="items[{{ $i }}][capacity]" value="{{ $item['capacity'] ?? '' }}"></td><td><input class="cq-input" name="items[{{ $i }}][finish_type]" value="{{ $item['finish_type'] ?? '' }}"></td><td><input class="cq-input" name="items[{{ $i }}][printing_type]" value="{{ $item['printing_type'] ?? '' }}"></td><td><input class="cq-input" type="number" step="0.01" name="items[{{ $i }}][unit_price]" value="{{ $item['unit_price'] ?? '' }}"></td><td><input class="cq-input" name="items[{{ $i }}][remarks]" value="{{ $item['remarks'] ?? '' }}"></td><td><button type="button" class="cq-remove" onclick="removeQuoteItemRow(this)">×</button></td></tr>@endforeach</tbody></table></div><button type="button" class="cq-btn cq-btn-light" id="addQuoteItemRow" style="margin-top:12px;">+ Add Item</button></div>
<div class="cq-section"><h3 class="cq-section-title">Totals & Terms</h3><div class="cq-grid"><div><label class="cq-label">Discount Type</label><select class="cq-select" name="discount_type"><option value="amount" @selected(old('discount_type',$quote->discount_type)==='amount')>Amount</option><option value="percent" @selected(old('discount_type',$quote->discount_type)==='percent')>Percent</option></select></div><div><label class="cq-label">Discount Value</label><input class="cq-input" type="number" step="0.01" name="discount_value" value="{{ old('discount_value',$quote->discount_value) }}"></div><div><label class="cq-label">GST / Tax %</label><input class="cq-input" type="number" step="0.01" name="tax_percent" value="{{ old('tax_percent',$quote->tax_percent) }}"></div><div><label class="cq-label">Shipping Amount</label><input class="cq-input" type="number" step="0.01" name="shipping_amount" value="{{ old('shipping_amount',$quote->shipping_amount) }}"></div><div><label class="cq-label">Payment Terms</label><input class="cq-input" name="payment_terms" value="{{ old('payment_terms',$quote->payment_terms) }}"></div><div><label class="cq-label">Delivery Time</label><input class="cq-input" name="delivery_time" value="{{ old('delivery_time',$quote->delivery_time) }}"></div><div class="cq-field full"><label class="cq-label">Notes</label><textarea class="cq-textarea" name="notes">{{ old('notes',$quote->notes) }}</textarea></div><div class="cq-field full"><label class="cq-label">Terms & Conditions</label><textarea class="cq-textarea" name="terms_conditions">{{ old('terms_conditions',$quote->terms_conditions) }}</textarea></div></div></div>
<div class="cq-actions"><a href="{{ $isEdit ? route('lead-quotes.show',$quote) : route('lead-quotes.index') }}" class="cq-btn cq-btn-light">Cancel</a><button class="cq-btn cq-btn-primary" type="submit">{{ $isEdit ? 'Update Quote' : 'Create Quote' }}</button></div>
</form></div>
<template id="quoteItemRowTemplate"><tr><td><input class="cq-input" name="items[__INDEX__][product_name]"></td><td><input class="cq-input" name="items[__INDEX__][description]"></td><td><input class="cq-input" type="number" step="0.001" name="items[__INDEX__][quantity]" value="1"></td><td><input class="cq-input" name="items[__INDEX__][unit]" value="pcs"></td><td><input class="cq-input" name="items[__INDEX__][capacity]"></td><td><input class="cq-input" name="items[__INDEX__][finish_type]"></td><td><input class="cq-input" name="items[__INDEX__][printing_type]"></td><td><input class="cq-input" type="number" step="0.01" name="items[__INDEX__][unit_price]"></td><td><input class="cq-input" name="items[__INDEX__][remarks]"></td><td><button type="button" class="cq-remove" onclick="removeQuoteItemRow(this)">×</button></td></tr></template>

@push('scripts')
    <script src="{{ asset('assets/js/lead-quotes.js') }}"></script>
@endpush
@endsection
