@extends('layouts.app')

@section('page-title', 'Customer Quote Detail')

@section('content')
@push('styles')
    <link rel="stylesheet" href="{{ asset('assets/css/lead-quotes-show.css') }}">
@endpush
<div class="cq-show"><div class="cq-card cq-header"><div><h1>{{ $quote->quote_number }}</h1><p>{{ $quote->title }} · {{ $quote->lead?->lead_number ?: 'Standalone Quote' }}</p></div><div class="cq-actions"><a href="{{ route('lead-quotes.index') }}" class="master-btn master-btn-light">Back</a><a href="{{ route('lead-quotes.edit',$quote) }}" class="master-btn master-btn-primary">Edit Quote</a>@if($quote->lead)<a href="{{ route('leads.show',$quote->lead) }}" class="master-btn master-btn-soft">View Lead</a>@endif</div></div>@if(session('success'))<div class="cq-alert">{{ session('success') }}</div>@endif
<div class="cq-grid"><div><div class="cq-card cq-section"><h3>Quote Overview</h3><div class="cq-info-grid"><div class="cq-info"><span>Status</span><strong><span class="cq-badge status-{{ $quote->status }}">{{ $quote->statusLabel() }}</span></strong></div><div class="cq-info"><span>Customer</span><strong>{{ $quote->client?->company_name ?? $quote->customer_company_name ?? '-' }}</strong></div><div class="cq-info"><span>Contact</span><strong>{{ $quote->customer_contact_name ?: '-' }}</strong></div><div class="cq-info"><span>Email / Mobile</span><strong>{{ $quote->customer_email ?: '-' }} {{ $quote->customer_mobile ?: '' }}</strong></div><div class="cq-info"><span>Quote Date</span><strong>{{ $quote->quote_date ? $quote->quote_date->format('d M Y') : '-' }}</strong></div><div class="cq-info"><span>Valid Until</span><strong>{{ $quote->valid_until ? $quote->valid_until->format('d M Y') : '-' }}</strong></div></div></div><div class="cq-card cq-section"><h3>Quote Items</h3><div class="cq-wrap"><table class="cq-table"><thead><tr><th>Product</th><th>Qty</th><th>Finish</th><th>Printing</th><th>Rate</th><th>Amount</th></tr></thead><tbody>@forelse($quote->items as $item)<tr><td>{{ $item->product_name }}<br><small>{{ $item->description }}</small></td><td>{{ $item->quantity }} {{ $item->unit }}</td><td>{{ $item->finish_type ?: '-' }}</td><td>{{ $item->printing_type ?: '-' }}</td><td>{{ $quote->currency }} {{ number_format((float)$item->unit_price,2) }}</td><td>{{ $quote->currency }} {{ number_format((float)$item->amount,2) }}</td></tr>@empty<tr><td colspan="6">No items added.</td></tr>@endforelse</tbody></table></div></div></div><div><div class="cq-card cq-section"><h3>Total Amount</h3><div class="total">{{ $quote->currency }} {{ number_format((float)$quote->total_amount,2) }}</div><div class="cq-info-grid" style="grid-template-columns:1fr;margin-top:16px"><div class="cq-info"><span>Subtotal</span><strong>{{ number_format((float)$quote->subtotal,2) }}</strong></div><div class="cq-info"><span>Discount</span><strong>{{ number_format((float)$quote->discount_amount,2) }}</strong></div><div class="cq-info"><span>Tax</span><strong>{{ number_format((float)$quote->tax_amount,2) }}</strong></div><div class="cq-info"><span>Shipping</span><strong>{{ number_format((float)$quote->shipping_amount,2) }}</strong></div></div></div><div class="cq-card cq-section"><h3>Terms</h3><p style="color:#536079;font-weight:700;line-height:1.6">Payment: {{ $quote->payment_terms ?: '-' }}<br>Delivery: {{ $quote->delivery_time ?: '-' }}<br><br>{{ $quote->terms_conditions ?: 'No terms added.' }}</p></div><div class="cq-card cq-section"><h3>Notes</h3><p style="color:#536079;font-weight:700;line-height:1.6">{{ $quote->notes ?: 'No notes added.' }}</p></div></div></div></div>
@endsection
