@extends('client_portal.layouts.app')

@section('title', $quote->quote_number)
@section('page-title', 'Quotation Detail')

@section('content')
<div class="cp-page-head"><div><p class="cp-eyebrow">{{ $quote->quote_number }}</p><h1>{{ $quote->title }}</h1><p>{{ $quote->currency }} {{ number_format((float)$quote->total_amount, 2) }} · {{ $quote->statusLabel() }}</p></div><div style="display:flex;gap:10px;flex-wrap:wrap;"><a href="{{ route('customer-quotes.public', $quote->public_token) }}" target="_blank" class="cp-btn cp-btn-primary">Open Public Quote</a><a href="{{ route('client-portal.quotes.index') }}" class="cp-btn cp-btn-light">Back</a></div></div>
<div class="cp-grid-4" style="margin-bottom:18px;"><div class="cp-card cp-stat"><span>Quote Date</span><strong>{{ optional($quote->quote_date)->format('d M Y') ?: '-' }}</strong></div><div class="cp-card cp-stat"><span>Expiry</span><strong>{{ optional($quote->expiry_date)->format('d M Y') ?: '-' }}</strong></div><div class="cp-card cp-stat"><span>Status</span><strong>{{ $quote->statusLabel() }}</strong></div><div class="cp-card cp-stat"><span>Total</span><strong>{{ $quote->currency }} {{ number_format((float)$quote->total_amount, 2) }}</strong></div></div>
<div class="cp-card" style="padding:20px;margin-bottom:18px;"><p class="cp-eyebrow">Items</p><h2 style="margin-top:0;">Quote Items</h2><div class="cp-table-wrap"><table class="cp-table"><thead><tr><th>Product</th><th>Qty</th><th>Unit Price</th><th>Amount</th></tr></thead><tbody>@foreach($quote->items as $item)<tr><td><strong>{{ $item->product_name }}</strong><span class="cp-muted" style="display:block;">{{ $item->description }}</span></td><td>{{ number_format((float)$item->quantity, 3) }} {{ $item->unit }}</td><td>{{ $quote->currency }} {{ number_format((float)$item->unit_price, 2) }}</td><td>{{ $quote->currency }} {{ number_format((float)$item->amount, 2) }}</td></tr>@endforeach</tbody></table></div></div>
<div class="cp-grid-2"><div class="cp-card" style="padding:20px;"><p class="cp-eyebrow">Terms</p><h2 style="margin-top:0;">Commercial Details</h2><p><strong>Payment Terms:</strong><br>{{ $quote->payment_terms ?: '-' }}</p><p><strong>Delivery:</strong><br>{{ $quote->delivery_terms ?: '-' }} {{ $quote->delivery_time ?: '' }}</p><p><strong>Notes:</strong><br>{{ $quote->notes ?: '-' }}</p></div><div class="cp-card" style="padding:20px;"><p class="cp-eyebrow">Comments</p><h2 style="margin-top:0;">Discussion</h2><form method="POST" action="{{ route('client-portal.quotes.comments.store', $quote->id) }}" style="margin-bottom:15px;">@csrf<div class="cp-field"><label>Comment</label><textarea name="body" required></textarea></div><button class="cp-btn cp-btn-primary" style="margin-top:10px;">Submit Comment</button></form>@forelse($comments as $comment)<div class="cp-comment"><div class="cp-comment-head"><strong>{{ $comment->authorName() }}</strong><span>{{ $comment->created_at->format('d M Y, h:i A') }}</span></div><p>{{ $comment->body }}</p></div>@empty<div class="cp-empty">No comments yet.</div>@endforelse</div></div>
@endsection
